project:
  type: website

website:
  title: "Digital Decade Dashboard"
  sidebar:
    collapse-level: 1
    contents:
      - href: index.qmd
        text: About
      - href: dashboard.qmd
        text: Dashboard
      - section: "Digital Business"
        contents:
          - href: businesses.qmd
          - text: Project Description
    background: "#f1de67"
    align: center
    tools:
      - icon: github
        href: https://github.com/CozminaSecula
        text: "GitHub"
      - icon: linkedin
        href: https://www.linkedin.com/in/cozminasecula/
        text: "Linkedin"
      - icon: envelope
        href: mailto:cozmina.secula@gmail.com
        text: "Email"


    style: docked
    search: true



  page-footer:
    right: "Built with [Quarto](https://quarto.org/)."
    left: "&copy; 2024 [Cozmina Secula](https://cozminasecula.github.io/blog/)"
    background: "#f1de67"



  open-graph: true


format:
  html:
    theme: [simplex, custom.scss]
    toc: true


execute:
  freeze: auto

editor: visual



