project:
  type: website

website:
  page-navigation: true
  reader-mode: true
  title: "Digital Decade Dashboards"
  description: "A series of dashboards that show data related to Europe's Digital Decade"

  sidebar:
    background: "#f1de67"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/CozminaSecula
        text: "GitHub"
      - icon: linkedin
        href: https://www.linkedin.com/in/cozminasecula/
        text: "Linkedin"
      - icon: envelope
        href: mailto:cozmina.secula@gmail.com
        text: "Email"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "About Digital Dasboards"
        contents:
          - href: about.qmd
            text: Overview

      - section: "Topics"
        contents:
          - href: ./dashboards/digital_business.qmd
            text: Digital Business




  page-footer:
    right: "Built with [Quarto](https://quarto.org/)."
    left: "&copy; 2024 [Cozmina Secula](https://cozminasecula.github.io/blog/)"
    background: "#f1de67"


  open-graph: true


format:
  html:
    theme: [simplex, custom.scss]
    toc: true


execute:
  freeze: auto

editor: visual



