project:
  type: website

website:
  title: "digital_decade_dashboard"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: dashboard.qmd
        text: Dashboard


format:
  html:
    theme: [cosmo, custom.scss]
    toc: true

execute:
  freeze: true



