project:
  type: website

website:
  title: "Digital Decade Dashboard"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: dashboard.qmd
        text: Dashboard

    background: light
format:
  html:
    theme: [cosmo, custom.scss]
    toc: true

execute:
  freeze: true



